### ISSUE TITLE
二维码过期了。。。

### ISSUE THREAD

**Issue by leiwen83** [codefuse-ai/CodeFuse-Query#25]

**Comment by zhouang777** [comment]
我先上传一个新的二维码暂时应急，但依然还是需要解决7天过期的问题，issue先留着

**Comment by ValKmjolnir** [comment]
新二维码已更新，12.28前有效: [图片链接](https://github.com/codefuse-ai/CodeFuse-Query/blob/main/assets/wechat_qrcode.JPG)

**Comment by zhouang777** [comment]
已更新在readme首页，使用企业微信的永久二维码
