### ISSUE TITLE
运行python的圈复杂度计算结果为空

### ISSUE THREAD

**Issue by 18140663659** [codefuse-ai/CodeFuse-Query#30]
您好，我在linux上的一个简单的python程序上运行计算圈复杂度的代码的时候执行结果为空

【python代码】

a = 10

for i in range(10):
    print("test")

【gdl文件】

// script
use coref::python::*

fn default_db() -> PythonDB {
    return PythonDB::load("coref_python_src.db")
}

/**
 * Get cyclomatic complexity of functions
 *
 * @param name   function name
 * @param value  cyclomatic complexity of function
 * @param path   path of file including this function
 * @param sline  function start line
 * @param eline  function end line
 */
fn getCyclomaticComplexity(
    name: string,
    value: int,
    path: string,
    sline: int,
    eline: int) -> bool {
    // get metric function
    for (c in MetricFunction(default_db())) {
        if (path = c.getLocation().getFile().getRelativePath() &&
            name = c.getQualifiedName() &&
            value = c.getCyclomaticComplexity() &&
            sline = c.getLocation().getStartLineNumber() &&
            eline = c.getLocation().getEndLineNumber()) {
            return true
        }
    }
}

fn main() {
    output(getCyclomaticComplexity())
}

【运行指令】
./sparrow-cli/sparrow database create -s test_java -lang java -o ./db_java/
./sparrow-cli/sparrow query run -d ./db_java/ -gdl test2.gdl -o ./

**Comment by FunJim** [comment]
您好，圈复杂度的计算是基于函数维度的，对应的 API 是 https://codefuse-ai.github.io/CodeFuse-Query/godel-api/python/schema/MetricFunction.html#metricfunctiongetcyclomaticcomplexity ，定义在函数体外面的代码是不进行计算的。

你可以修改代码，改成用函数来进行定义，比如这样：

```python
a = 10

def test():
    for i in range(10):
        print("test")
```

返回的查询结果：

```json
[{"name": "test", "value": 2, "path": "test.py", "sline": 3, "eline": 5}]
```

另外，您调用`sparrow database create`的命令好像有问题，`-lang` 传入的应该是`python`

**Comment by 18140663659** [comment]
嗯嗯，换成项目中提供的request项目就正常了，readme里的微信链接过期了，请问有新的链接吗

**Comment by FunJim** [comment]
> 嗯嗯，换成项目中提供的request项目就正常了，readme里的微信链接过期了，请问有新的链接吗

https://github.com/codefuse-ai/CodeFuse-Query/pull/31 更新了二维码。

Closing this one.
