### ISSUE TITLE
有和gitlab联动获取代码以及diff的说明文档么？

### ISSUE THREAD

**Issue by fangyuanrui** [codefuse-ai/CodeFuse-Query#37]
有和gitlab联动获取代码以及diff的说明文档么？

**Comment by zhouang777** [comment]
可能我理解有误，看描述你要的是一套和代码托管平台联动的服务。在公司内部我们搭建了这样一套服务，订阅webhook并集成到CR中。但这并非本项目提供的能力。
CodeFuse-Query 提供的是分析引擎，针对的是本地代码仓库，不会与具体的代码托管平台产生交互。

**Comment by fangyuanrui** [comment]
就是当代码有修改后，就重新拉取最新代码重新解析一遍入库么？至于变更范围这些其实还是基于最新代码去做的一些查询和分析？

**Comment by zhouang777** [comment]
是的。变更的的分析能力，可以用git diff获取变更文件后再分析，也可以拿前后两次分析结果处理得到。目前这个能力不会做到引擎中
