### ISSUE TITLE
能不能搞个一键安装的dock镜像

### ISSUE THREAD

**Issue by fangyuanrui** [codefuse-ai/CodeFuse-Query#38]
能不能搞个一键安装的dock镜像

**Comment by zhouang777** [comment]
请参考在线教程：https://github.com/codefuse-ai/CodeFuse-Query/blob/main/tutorial/README.md 。
CodeSpace 打开后，命令行就可以直接执行 sparrow 命令：
![image](https://github.com/codefuse-ai/CodeFuse-Query/assets/19465959/c17cc758-e9dc-449f-848c-0a3931e08d59)
