### ISSUE TITLE
有方法到入口的调用链路的查询范例么？

### ISSUE THREAD

**Issue by fangyuanrui** [codefuse-ai/CodeFuse-Query#39]
有方法到入口的调用链路的查询范例么？
看了解析的数据结构有点懵

**Comment by fangyuanrui** [comment]
还有控制流程图的获取范例有吗

**Comment by ValKmjolnir** [comment]
调用链路可以参考这个脚本 [CallChain.gdl](https://github.com/codefuse-ai/CodeFuse-Query/tree/main/example/java/CallChain.gdl)

```rust
pub fn specified_callable_signature(name: string) -> bool {
    // give specified callables' signatures here
    [
        {"com.alipay.demo.Main.test:void()"},
        {"xxx"},
        {"xxx"}
    ]
}
```
在上面这个方法里填上你需要搜索的接口签名，这个地方我给了一个样例签名。

**Comment by zhouang777** [comment]
CFG 问题在另一个issue中追踪  https://github.com/codefuse-ai/CodeFuse-Query/issues/48
