### ISSUE TITLE
代码数据模型COREF 部分的源码还没有开源吗？

### ISSUE THREAD

**Issue by sevenpy** [codefuse-ai/CodeFuse-Query#44]
您好：
请教一下，代码数据模型COREF 部分的源码还没有开源吗？如果有开源的话，源码是哪一部分呢？ 非常感谢！

**Comment by zhouang777** [comment]
已经开源。这部分是用我们自己的数据处理语言Godel书写的。各语言的模型 请参考language/{lang}/lib 目录
