### ISSUE TITLE
Find callers of a method 查找方法的调用方并输出调用链

### ISSUE THREAD

**Issue by busychen** [codefuse-ai/CodeFuse-Query#58]
已知方法签名a，想要查询哪些方法调用了a，一直往上查找，直到最上层方法，并输出从最上层方法到a的所有链路

**Comment by ValKmjolnir** [comment]
@zaqcxy updated an example for this: [example/java/CallChainWithSignature.gdl](https://github.com/codefuse-ai/CodeFuse-Query/blob/main/example/java/CallChainWithSignature.gdl)

**Comment by busychen** [comment]
> @zaqcxy updated an example for this: [example/java/CallChainWithSignature.gdl](https://github.com/codefuse-ai/CodeFuse-Query/blob/main/example/java/CallChainWithSignature.gdl)

谢谢回复，如果想在callMethodName和calleeMethodName添加参数类型，类似这种callMethodName(java.lang.String)怎么修改脚本

**Comment by ValKmjolnir** [comment]
> > @zaqcxy updated an example for this: [example/java/CallChainWithSignature.gdl](https://github.com/codefuse-ai/CodeFuse-Query/blob/main/example/java/CallChainWithSignature.gdl)
> 
> 谢谢回复，如果想在callMethodName和calleeMethodName添加参数类型，类似这种callMethodName(java.lang.String)怎么修改脚本

你是指带参数的函数签名？如果是带参数的函数签名可以用样例里的 [example/java/GetSignature.gdl](https://github.com/codefuse-ai/CodeFuse-Query/blob/main/example/java/GetSignature.gdl) 看看给的 callable 签名长啥样，然后复制下来就行

**Comment by busychen** [comment]
thanks for your reply 我将关闭问题
