### ISSUE TITLE
增量创建数据库 [ incremental extract ]

### ISSUE THREAD

**Issue by busychen** [codefuse-ai/CodeFuse-Query#62]
怎么增量创建数据库

**Comment by zhouang777** [comment]
目前只有Java抽取支持文件级别的增量抽取。命令如下：
``` shell
sparrow database create -s ./src -lang java -o . --extraction-config java.incremental=true java.cache-dir=./coref-cache java.commit=abc
```
逐个解释一下参数
- ```incremental=true```：表示开启增量。
- ```cache-dir=./coref-cache```：增量需要用到缓存，必须指定缓存的存储目录。
- ```commit=abc```：增量需要指定版本信息，这里使用的参数是commit，但实际传入的参数可以是任意字符串用来标识代码版本。
