### ISSUE TITLE
对非本项目的java类，无完整识别的标识

### ISSUE THREAD

**Issue by ditunes** [codefuse-ai/CodeFuse-Query#77]
这个是method 表数据 ·com.alibaba.bizworks.mdserver.pilot.service.domainModelData.agent.adl.grammer.BWDLParser.Builtin_generic_typeContext.accept:T(ParseTreeVisitor<? extends T>):<T> 你看 ParseTreeVisitor 是其他包的类此时就只是一个名称，没有完整标识

**Comment by zhouang777** [comment]
这是一个依赖解析问题。
默认情况下，CodeFuse-Query 只会解析源码中的类，此时 ParseTreeVisitor 就找不到完整类名，因为没有足够的信息。
但当你能提供这个类名所在的 jar 包时，就可以解析出完整类名。这个机制就和编译一样，如果缺 jar 包就编译不过。
你可以通过添加抽取 -classpath 选项来指定额外的解析范围。如下例子：
``` sparrow database create -s ${repo_dir} -lang java -o . --extraction-config java.classpath=${path_to_jar}```
